### ISSUE TITLE
Search queries are fired twice

### ISSUE THREAD

**Issue by tarleb** [Sammaye/yii2-solr#5] opened 2015-12-16 10:47 UTC
Using the SolrDataProvider will lead to the query being send twice if pagination is not disabled.  This is caused by the `getTotalCount` function, which copies the main query and sends it again just to retrieve the number of documents found.

Performance effects are negligible, as Solr should usually cache the query result.  The second query is basically free.  It might still be cleaner to fire the query just once and to store the result in an object variable.

Anyway, thanks for writing this in the first place, very useful :fireworks:

**Comment by Sammaye** [comment] 2015-12-16 10:51
The problem is that it is two different queries. This is why pagination in most DBs is two queries. Onme is to count and one is to fetch the results

**Comment by Sammaye** [comment] 2015-12-16 10:51
I will check this out though incase I have made some kind of common mistake

**Comment by tarleb** [comment] 2015-12-16 11:24
Sam Millman <notifications@github.com> writes:

> The problem is that it is two different queries. This is why pagination in
> most DBs is two queries. Onme is to count and one is to fetch the results

In that case, it would make sense to set the number of returned rows to
0 for the counting query (instead of using the default).  Would save a
few bytes ;)

**Comment by Sammaye** [comment] 2015-12-16 11:28
Yeah, probably I mean I wrote it a while ago so I am trying to remember why
I did it this way, whether I just didn't care too much about this or
whether I saw something that meant it didn't matter.

I'll take a look.

**Comment by Sammaye** [comment] 2015-12-31 11:55
I remember why now: `getSort()` This can be fired before the sort is actually set, especially if you set a dynamic sort and many do (I do at times, especially with facets). So I took the lesser evil and just said that `totalCount` and the actual display of the results are separate queries.

I am gonna close this for that reason, feel free to reopen if I am wrong.

**Closed by Sammaye** 2015-12-31 11:55 UTC

**Comment by tarleb** [comment] 2016-01-01 17:38
I didn't have that use-case yet, but it sounds like that makes sense. Thanks for looking into it.
